/* Configuration for testgnatsolor1 generated by Alire */
#ifndef TESTGNATSOLOR1_CONFIG_H
#define TESTGNATSOLOR1_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "testgnatsolor1"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
