--  ============================================================================
--  VERSION.ADS — Auto-generated by scripts/update_version.sh
--  DO NOT EDIT BY HAND — regeneration overwrites this file.
--  ============================================================================
package Version is
   Project_Name : constant String := "Project Zephyrine Adelaide Volatus Damare AWS";
   Git_Hash     : constant String := "d5e42cc";
   Full_Version : constant String := Project_Name & " - " & Git_Hash;
end Version;
