(* Auto-generated Coq translation of src/python/code_tool.py *)
(* Generated by sabotage_verifier.py Python→Coq translator *)
(* WARNING: This is a structural translation — proofs may need manual refinement *)

Module code_tool.

Require Import ZArith.
Require Import QArith.
Require Import Strings.String.
Require Import Lists.List.
Require Import Bool.
Open Scope Z_scope.
Open Scope string_scope.

(* No translateable functions found *)
(* Translator requires functions with type hints *)
End code_tool.

(* End of auto-generated Coq translation *)