(* Auto-generated Coq translation of src/c_bindings/stderr_suppress.c *)
(* Generated by sabotage_verifier.py C→Coq translator *)
(* WARNING: Structural translation — proofs may need manual refinement *)
(* Based on CompCert C-to-Coq methodology *)

Module stderr_suppress.

Require Import ZArith.
Require Import QArith.
Require Import Strings.String.
Require Import Lists.List.
Require Import Bool.
Open Scope Z_scope.
Open Scope string_scope.

(** Function suppress_dup — C→Coq auto-translate *)
Definition suppress_dup : Z :=
  saved.

Theorem suppress_dup_correct :
  suppress_dup = ?.
Proof.
  (* TODO: Prove this obligation manually or with automation *)
  Admitted.

(** Function if — C→Coq auto-translate *)
Function if ((0 : Prop)) : Prop :=
  saved.

Theorem if_correct :
  forall (0 : Prop),
  if 0 = ?.
Proof.
  (* TODO: Prove this obligation manually or with automation *)
  Admitted.

(** Function suppress_restore — C→Coq auto-translate *)
Function suppress_restore ((saved_fd : Z)) : Z :=
  (0%Z).

Theorem suppress_restore_correct :
  forall (saved_fd : Z),
  suppress_restore saved_fd = ?.
Proof.
  (* TODO: Prove this obligation manually or with automation *)
  Admitted.

(** Function if — C→Coq auto-translate *)
Function if ((0 : Prop)) : Prop :=
  (0%Z).

Theorem if_correct :
  forall (0 : Prop),
  if 0 = ?.
Proof.
  (* TODO: Prove this obligation manually or with automation *)
  Admitted.

End stderr_suppress.

(* End of auto-generated Coq translation *)