(* Auto-generated Coq translation of src/c_bindings/supertonic/supertonic_c_api.h *)
(* Generated by sabotage_verifier.py C→Coq translator *)
(* WARNING: Structural translation — proofs may need manual refinement *)
(* Based on CompCert C-to-Coq methodology *)

Module supertonic_c_api.

Require Import ZArith.
Require Import QArith.
Require Import Strings.String.
Require Import Lists.List.
Require Import Bool.
Open Scope Z_scope.
Open Scope string_scope.

(* No translateable functions found *)
End supertonic_c_api.

(* End of auto-generated Coq translation *)