(* Auto-generated Coq translation of src/Util/fix_indentation.py *)
(* Generated by sabotage_verifier.py Python→Coq translator *)
(* WARNING: This is a structural translation — proofs may need manual refinement *)

Module fix_indentation.

Require Import ZArith.
Require Import QArith.
Require Import Strings.String.
Require Import Lists.List.
Require Import Bool.
Open Scope Z_scope.
Open Scope string_scope.

(* No translateable functions found *)
(* Translator requires functions with type hints *)
End fix_indentation.

(* End of auto-generated Coq translation *)