--  Configuration for ncursesada generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Ncursesada_Config is
   pragma Pure;

   Crate_Version : constant String := "6.5.0";
   Crate_Name : constant String := "ncursesada";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "aarch64";

   Alire_Host_Distro : constant String := "homebrew";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Ncursesada_Config;
