#!/bin/bash
# ============================================================================
# update_version.sh — Regenerate src/version.ads with current git hash
# ============================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_FILE="$PROJECT_ROOT/src/version.ads"

cd "$PROJECT_ROOT"

HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "0000000")

cat > "$VERSION_FILE" <<EOF
--  ============================================================================
--  VERSION.ADS — Auto-generated by scripts/update_version.sh
--  DO NOT EDIT BY HAND — regeneration overwrites this file.
--  ============================================================================
package Version is
   Project_Name : constant String := "Project Zephyrine Adelaide Volatus Damare AWS";
   Git_Hash     : constant String := "${HASH}";
   Full_Version : constant String := Project_Name & " - " & Git_Hash;
end Version;
EOF

echo "[version] Updated version.ads with hash: ${HASH}"
