#!/bin/bash
#Wrapper to launch exec_L1 from osascript Launching Terminal
echo "Extracting Wrapper L1"
cat > /tmp/exec_L1 << EOL
#!/bin/bash

# Check if brew command is detected, if not, install Homebrew
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Update Homebrew
echo "Updating Homebrew..."
brew update

# Upgrade installed packages
echo "Upgrading installed packages..."
brew upgrade

# Update Homebrew
echo "Updating Homebrew..."
brew update

# Check if git command is detected, if not, install it using brew
if ! command -v git &> /dev/null; then
    echo "Installing git..."
    brew install git 
fi

# Check if run.sh script exists, if not, clone the repository
if [ ! -f "\$HOME/adelaide-zephyrine-charlotte-assistant/launchcontrol/run.sh" ]; then
    echo "Cloning repository..."
    git clone --depth=1 https://github.com/albertstarfield/alpaca-electron-zephyrine "\$HOME/adelaide-zephyrine-charlotte-assistant"
fi

# Launch terminal and execute run.sh script
echo "Launching terminal..."
osascript -e 'tell application "Terminal" to do script "bash \$HOME/adelaide-zephyrine-charlotte-assistant/launchcontrol/run.sh"'

# Sleep for 15 seconds
echo "Waiting for 15 seconds..."
sleep 15

open -a safari

EOL
osascript -e 'tell application "Terminal" to do script "/bin/bash -c \"bash /tmp/exec_L1 ; rm /tmp/exec_L1 ; exit\"'\"
sleep 60