/* Configuration for system_info generated by Alire */
#ifndef SYSTEM_INFO_CONFIG_H
#define SYSTEM_INFO_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "system_info"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
